services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4444:4444"

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    depends_on:
      - server
    command: ["./kvbench", "server", "4444"]