FROM debian:bookworm-slim AS builder 

RUN apt-get update && \ 
    apt-get install -y build-essential && \ 
    rm -rf /var/lib/apt/lists/* 
WORKDIR /app 
COPY . . 
RUN g++ client.cpp -O2 -o kvclient 

FROM debian:bookworm-slim 
WORKDIR /app 
COPY --from=builder /app/kvclient . 
ENTRYPOINT ["./kvclient"]