FROM cmake:4.2 AS builder 

RUN apt-get update && \ 
    apt-get install -y build-essential && \ 
    rm -rf /var/lib/apt/lists/* 

WORKDIR /app 

COPY . . 

RUN cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
RUN cmake --build build --target kvclient

FROM debian:bookworm-slim 
WORKDIR /app 
COPY --from=builder /app/build/kvclient /app/kvclient

ENTRYPOINT ["./kvclient"]